config/routes.rb
Rails.application.routes.draw do
  root 'welcome#dashboard'
  get '/products' => 'product#list', as: :product
  get '/products/:pid' => 'product#show', as: :products

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/product_controller.rb
require 'csv'
class ProductController < ApplicationController
    class Product
        attr_accessor :pid, :item, :description, :price, :condition,
                      :condition, :dimension_w, :dimension_l, :dimension_h, :img_file,
                      :quantity, :category, :clearance
    end

    def list
        @products = in_stock
    end

    def show
        products = discount
        @product = products.find { |p| p.pid == params[:pid] }
    end


    def fetch_products
        products = []

        CSV.foreach("#{Rails.root}/data-import/mf_inventory.csv", headers: true) do |row|
            product_hash = row.to_hash
            product = Product.new
            product.pid = product_hash['pid']
            product.item = product_hash['item']
            product.description = product_hash['description']
            product.price = product_hash['price'].to_f
            product.condition = product_hash['condition'].to_s
            product.dimension_w = product_hash['dimension_w']
            product.dimension_l = product_hash['dimension_l']
            product.dimension_h = product_hash['dimension_h']
            product.img_file = product_hash['img_file']
            product.quantity = product_hash['quantity'].to_i
            product.category = product_hash['category']


            products << product
        end

        products
    end

    def in_stock
      stocked = []
      product = discount
      product.each do |product|
        if product.quantity > 0
          stocked << product
      end

      end
    end

    def discount
      product = fetch_products
      product.each do |product|
        if product.condition == "good"
          product.price = product.price*0.9
          product.clearance = "Items on clearance"
        elsif product.condition == "average"
          product.price = product.price*0.8
          product.clearance = "Items on clearance"

        else
        end
      end
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def dashboard

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MalloryFurniture</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/product/list.html.erb
<h1 class= "page_title">
  <%= link_to root_path, class: "title_text" do%>
  Mallory Furniture
  <% end%>
</h1>

<% @products.in_groups_of(3, false) do |products| %>
  <div class="row">
    <% products.each do |product| %>
      <div class="col-xs-4">
        <div class="thumbnail">
          <%= link_to product_path(id: product.pid) do %>
            <%= image_tag product.img_file, class: "small" %>
          <% end %>
          <div class="caption">
            <h3><%= product.item %></h3>
            <p><%= number_to_currency product.price %></p>
            <%= link_to 'More Info', products_path(pid: product.pid), class: 'btn btn-primary btn-block' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/product/show.html.erb
<h1 class= "page_title">
  <%= link_to root_path, class: "title_text" do%>
  Mallory Furniture
  <% end%>
</h1>
<div class="container-fluid yield">
<div class="row">
    <div class="col-xs-8">
        <div class="image thumbnail">
            <%= image_tag @product.img_file, class: "large"%>
        </div>
    </div>
    <div class="col-xs-4 info">
        <h1 class="name"><%= @product.item %></h1>
        <h3 class="price">Price: <%= @product.price %></h3>
        <h3 class ="sale"><%= @product.clearance %></h3>
        <h3 class="description">Description</h3>
          <%= @product.description %>
        <br>
        <h3 class="dimensions">Dimensions</h3>
        <p>
          Length: <%= @product.dimension_l %>
        </p>
        <p>
          Width: <%= @product.dimension_w %>
        </p>
        <p>
          Height: <%= @product.dimension_h %>
        </p>
    </div>
</div>
</div>

app/views/welcome/dashboard.html.erb
<h1 class= "page_title">
  <%= link_to root_path, class: "title_text" do%>
  Mallory Furniture
  <% end%>
</h1>


<div class="jumbo">
  <div class="littlebox">
    <div class="page-header">
      <h1>Your furniture is old<h1>
      <div class="text-right"><small>Ours is older.</small></div>

    </div>
    <p>
      <%= link_to "Checkout our products", product_path, class: "checkout_products"%>
    </p>
  </div>



</div>